name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: [self-hosted, ostad-runner-label]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo cp index.html /var/www/qr-studio/index.html
          echo "HTML updated successfully."

      - name: Test
        run: |
          curl -f http://localhost:1338
          echo "Website test passed."
